### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by ssgelm** [kendfinger/virtual#2]
I'm trying to get this to run on my M1 macbook air and I'm not having any luck. I'm trying to boot the Debian installer. I built the binary using xcode (built with a Release profile). Initially I grabbed the netboot kernel and initrd (which should be able to boot fully with no additional disk) but I also tried adding the installer iso and have had no luck. I tried running it with
```
$ ./virtual -k installer-kernel -r installer-initrd -d debian-10.6.0-arm64-netinst.iso -c "console=hvc0,9800"
```
and also a bunch of other permutations but I haven't had any luck. Any tips on what I need to do to get this to run?

**Comment by woachk** [comment]
Hello,

You'll need to unzip your installer-kernel beforehand if it's compressed. Rename it to installer-kernel.gz/bz2/whatever your format is and uncompress it. That uncompressed kernel can then be loaded.

(tested with Ubuntu though)

**Comment by ssgelm** [comment]
Looks like the installer isn't compressed:
```
$ file installer-kernel
installer-kernel: Linux kernel ARM64 boot executable Image, little-endian, 4K pages
```
What ubuntu kernel, ramdisk, and disk did you try? I'd like to get it booted once and then I can try and shoehorn in other distros ;)

**Comment by woachk** [comment]
@ssgelm 
Arguments: console=hvc0
Choose Ubuntu Server, extract vmlinuz and initrd from that image and rename vmlinuz to vmlinuz.gz + extract that.

![image](https://user-images.githubusercontent.com/24752637/99824594-34537a80-2b56-11eb-8ab1-ca06772ef013.png)

**Comment by ssgelm** [comment]
Nice sounds super easy. I'll start there then. Thanks so much.

**Comment by woachk** [comment]
If you are on the latest build, this might be broken and you'd have to use https://github.com/KhaosT/SimpleVM. We are currently trying to figure out why.

**Comment by azenla** [comment]
I do not have an M1 machine as of yet (hopefully soon), but when I do, I want to build this tool out more. I'd love to take Pull Requests if anyone can contribute 👍

**Comment by ssgelm** [comment]
I am taking a look. If I get anything working I'll definitely PR it.

**Comment by cblackcom** [comment]
@kendfinger I have an M1 on my desk here now and would be happy to grant you access to it over the net if you like.  I'll send you a note on Twitter.

**Comment by azenla** [comment]
I may have resolved the issue in the latest commits. I would recommend trying again. Please note that NAT networking is optional and off by default, to enable, pass `-n` or `--network` to the options.

**Comment by cblackcom** [comment]
Confirmed fixed for me on Intel.  I'll try to give it a run on the M1 this weekend if no one beats me to the punch.

**Comment by ssgelm** [comment]
Fixed for me on M1 too!

**Comment by azenla** [comment]
Awesome! I appreciate everyone's help! To celebrate, I released version 0.0.1, and the tool is now available on Homebrew.

```
brew install kendfinger/tools/virtual
```

Please let me know of any suggestions. I intend to, over the course of the next few days, add a few subcommands to help with downloading distributions, and perhaps a friendly mode that will run Ubuntu/Fedora/etc. on demand. I've also considered adding a daemon mode that you can connect to.

**Comment by woachk** [comment]
@kendfinger note for that: you'll be better off using the cloud OS images, which have the proper OS installed and set up already (intended for AWS and co) instead of a .iso.

**Comment by azenla** [comment]
@woachk That is a great point, I tried that out and it's much better. I want to add cloud init support too, so you can boot with a cloud init disk.

If anyone has any feature requests, please feel free to file them as an issue. The [Goals](https://github.com/kendfinger/virtual/wiki/Goals) wiki page contains some of my thoughts around the project and where I intend to go with it.

**Comment by cblackcom** [comment]
@woachk @kendfinger Using PR #3 to specify a consistent MAC address I've got the networking going consistently between boots using the Ubuntu cloud images.  I'll probably do a writeup on a blog somewhere about this this evening so that it's easy for other people to get going.

**Comment by ssgelm** [comment]
Incidentally I still am totally unable to boot a debian kernel. I'm gonna try something more bleeding edge to see if maybe there's a minimum kernel version required to boot. Alternatively I can try diffing the kernel configs to see if there's anything obvious.

**Comment by woachk** [comment]
@ssgelm the Debian installer kernels don't have virtio it seems, but the ones for a proper installed Debian do.

Why? I don't know.

**Comment by ssgelm** [comment]
Hmm, even with the debian cloud image that has virtio I still get nothing:
```
$ grep -i virtio config-5.9.0-3-arm64
CONFIG_BLK_MQ_VIRTIO=y
CONFIG_VIRTIO_VSOCKETS=m
CONFIG_VIRTIO_VSOCKETS_COMMON=m
CONFIG_NET_9P_VIRTIO=m
CONFIG_VIRTIO_BLK=m
CONFIG_SCSI_VIRTIO=m
CONFIG_VIRTIO_NET=m
CONFIG_VIRTIO_CONSOLE=m
CONFIG_HW_RANDOM_VIRTIO=m
CONFIG_DRM_VIRTIO_GPU=m
CONFIG_VIRTIO=m
CONFIG_VIRTIO_MENU=y
CONFIG_VIRTIO_PCI=m
CONFIG_VIRTIO_PCI_LEGACY=y
CONFIG_VIRTIO_PMEM=m
CONFIG_VIRTIO_BALLOON=m
CONFIG_VIRTIO_INPUT=m
CONFIG_VIRTIO_MMIO=m
# CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES is not set
# CONFIG_VIRTIO_IOMMU is not set
# CONFIG_RPMSG_VIRTIO is not set
CONFIG_VIRTIO_FS=m
CONFIG_CRYPTO_DEV_VIRTIO=m
```

**Comment by apinske** [comment]
@ssgelm Did you find a kernel config that works?

**Comment by ssgelm** [comment]
No, I haven't had a chance to mess with it.

**Comment by praneet-suresh** [comment]
Check out https://github.com/PraneetNeuro/Project-Mendacius for a more user friendly experience in managing Linux VMs

**Comment by apinske** [comment]
I had some success with a minimal kernel. You can find my config here: https://github.com/apinske/simpleos/blob/master/macos/config-linux
I will try to get more stuff out, e.g. currently it fails to boot without ACPI, and I don't understand why yet.
